### ISSUE TITLE
Polmav lights

### ISSUE THREAD

**Issue by bloodyplayer** [AndroidModLoader/JPatch#8]
Add polmav search lights to activate again like ps2 version. 
Fix radio anim in water vehicles.

**Comment by D4elson** [comment]
There may also be the possibility of having the physics in the water when the cj falls and it sinks when it is a high or low altitude. In the PC version it does.

**Comment by BengbuGuards** [comment]
Stuntplane and cropduster also have their own fx. They can be actived by H on PC.

**Comment by BengbuGuards** [comment]
@RusJJ  There is already an operation to switch `bSearchLightEnabled` in the CHeli::ProcessControl function, but it doesn't work probably because of the broken CPad::HornJustDown function. I think you can simply fix it, which would be great. CPlane::ProcessControl does the same. Or have a look at my cleo mod at https://github.com/BengbuGuards/GTASA_Android_CLEOScripts. It just switch that bool simply.

**Comment by RusJJ** [comment]
> physics in the water

Coming in v1.4.3

**Comment by RusJJ** [comment]
> Fix radio anim in water vehicles.

Probably you meant Boat radio antenna rotating. In v1.4.3
In researching for searchlights, for now.

**Comment by bloodyplayer** [comment]
Thank u for responding bro
And can u help me 🙏
